repos: 
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    - id: isort
      args: ["--profile", "black"]

  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
    - id: black
      language_version: python3.9

  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        entry: sh -c 'pytest'
        language: system